/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:46f5e16c-fcb1-456b-8885-21eab325c1e0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_stUZpJlVO",
    "aws_user_pools_web_client_id": "26dgp6bdnatgbu53poaho3jpai",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xv6xdyupg5behpb2dmpflftkiu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "reactapp701629ded79864da2bd443795ae48688455814-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
